### ISSUE TITLE
Improved cmdline UX

### ISSUE THREAD

**Issue by desultory** [Biosias/uefi-mkconfig#13]
When using the efistub option for installkernel, this is used. It's not clear that users should probably configure the cmdline first. The default behavior will pull the cmdline from the install media which may not work.

I think there is a warning at runtime which is easy to miss. It would be nice if the ebuild warned users first, so they are aware of what config may be necessary.

**Comment by AndrewAmmerlaan** [comment]
> The default behavior will pull the cmdline from the install media which may not work.

As a side note, this is also the behaviour of systemd-boot, so perhaps some more general note about configuring the cmdline before installing the kernel should be added to the handbook somewhere.

**Comment by Biosias** [comment]
Indeed, I'll add a "Setup" question to the readme and also will put warning into ebuild.

Also will start work on gentoo wiki page for uefi-mkconfig.

**Comment by Biosias** [comment]
The newest version also now refuses to run unless configuration is present. This should mitigate the forgetting to create configuration problem.

**Comment by Biosias** [comment]
Done
