### ISSUE TITLE
Which are the dependencies?

### ISSUE THREAD

**Issue by kuraga** [Biosias/uefi-mkconfig#15]
Which are the dependencies?

I see the next calls:
* Bash itself,
* `efibootmgr`,
* `lsblk`,
* `find`,
* `sort`,
* `grep`,
* `head`,
* `tr`,
* `printf`,
* `mount`.

In README:
* (not specified)

Gentoo ebuild [dependencies](https://packages.gentoo.org/packages/sys-boot/uefi-mkconfig/dependencies):
* `app-shells/bash`,
* `sys-boot/efibootmgr`.

Thanks!

**Comment by Biosias** [comment]
That's about it. I'll add it to the ebuild for new version

**Comment by kuraga** [comment]
Thanks!
Will we be adding them to the README?

**Comment by AndrewAmmerlaan** [comment]
Packages that are part of the `@system` set should not be listed as dependencies in the ebuild.

**Comment by Biosias** [comment]
> Thanks! Will we be adding them to the README?

I don't see a for why not

**Comment by kuraga** [comment]
> Packages that are part of the `@system` set should not be listed as dependencies in the ebuild (i.e. dependencies in the ebuild are fine as they are).

@AndrewAmmerlaan , @Biosias `sys-apps/util-linux` (`lsblk`) isn't there, is it?

**Comment by AndrewAmmerlaan** [comment]
> > Packages that are part of the `@system` set should not be listed as dependencies in the ebuild (i.e. dependencies in the ebuild are fine as they are).
> 
> @AndrewAmmerlaan , @Biosias `sys-apps/util-linux` (`lsblk`) isn't there, is it?

It is in the system set

**Comment by kuraga** [comment]
> > > Packages that are part of the `@system` set should not be listed as dependencies in the ebuild (i.e. dependencies in the ebuild are fine as they are).
> > 
> > 
> > @AndrewAmmerlaan , @Biosias `sys-apps/util-linux` (`lsblk`) isn't there, is it?
> 
> It is in the system set

Hm.
https://gitweb.gentoo.org/repo/gentoo.git/tree/profiles/base/packages doesn't have it.
https://wiki.gentoo.org/wiki/Package_sets#.40system has it.

As a dependency, may be?

**Comment by AndrewAmmerlaan** [comment]
> https://gitweb.gentoo.org/repo/gentoo.git/tree/profiles/base/packages doesn't have it.

That's because that is not the system set. You can see from the colour in `eix` that `util-linux` is in the system set.

**Comment by kuraga** [comment]
> > Thanks! Will we be adding them to the README?
> 
> I don't see a reason for why not

#17
