### ISSUE TITLE
Part is not specified for entries

### ISSUE THREAD

**Issue by Lik-the-Fluffin** [Biosias/uefi-mkconfig#19]
efibootmgr has "--part" option with is defaulted to "1", but if UEFI system partition is not first on the disk invalid uefi entries would be created.
For example I have UEFI partition on /dev/nvme0n1p2 and it is detected, but part is defaulted to 1

invalid: Boot0001* Linux HD(**_1_**,GPT,
valid: Boot0001* Linux HD(**_2_**,GPT,

**Comment by Biosias** [comment]
Hello, I've found and fixed the issue. I'll release new version with the fix asap

**Comment by Biosias** [comment]
New version is released
