### ISSUE TITLE
Solution to uefi-mkconfig with chroot error  lsblk that can't see parttype

### ISSUE THREAD

**Issue by PerfMonk** [Biosias/uefi-mkconfig#23]
lsblk relies on udev. However, udev is not really functional within the chroot.

As a consequence, lsblk cannot display the parttype if it's run from within the chroot .

I found a workaround though: I can do a " mount --bind /run/udev /mnt/gentoo/run/udev "  before going in chroot, which is enough to at least query udev, and get lsblk to work as I expect.

I hope it could be corrected or at least published that /run/udev is needed by uefi-mkconfig to work in a chroot.

Regards,
        Bernard Tremblay

**Comment by AndrewAmmerlaan** [comment]
Bind mounting `/run` to `/mnt/gentoo/run` is already part of the chrooting instructions in the handbook. Though I suppose it does no harm to explicitly mention this again in the README here.

**Comment by Biosias** [comment]
Hello @PerfMonk ! Thank you very much!

@AndrewAmmerlaan I'll add it to the README and also add a check to the script itself. There are few edge cases I would like to add checks for anyway.

**Comment by PerfMonk** [comment]
I did use arch-chroot  (easier)  and it doesn't mount  /run .  That was firstly the problem :+1:
