### ISSUE TITLE
multiple efi entries for same kernel + custom label for efi entries

### ISSUE THREAD

**Issue by fabolous005** [Biosias/uefi-mkconfig#25]
Users should have the option to add multiple efi entries per kenel.
This would allow changing some important parameters on kernel commandline.

As some uefi's may follow different (or not at all) uefi specifications, some entries may be invalid.
Therefor we should allow the user to define a custom label.

**Comment by fabolous005** [comment]
Proposal for configuration:
To solve both problems at once, why not declare an associative array, where the key will be the efi entry and the value will be the kernel cmdline?
For the key it would be nice to have something like a `%v` or `%kernel` wildcard that will be replaced by the actual version.
The only problem i see with this, is sorting...
I thought about allowing the user to define a regex string that filters out cmdlines, that should be added after normal entries, but i'm not sure that's en elegant way, this also introduces a lot of new calls to efibootmgr.

But it would allow sorting like this:
```
linux-6.9.9
linux-6.9.8
linux-6.9.9 recovery
```

What do you think?

**Comment by Biosias** [comment]
Regarding calls to `efibootmgr` , we need to keep these at minimum. We've found out that some older UEFI firmwares are very slow so every call to `efibootmgr` introduces more and more delay to `uefi-mkconfig` .

Regarding "Custom labels", I just want to clarify what exactly do you mean. Now I understand it in a way that you would like to introduces something like customizable templates which will be used for naming the entries. Is this understanding correct?

**Comment by AndrewAmmerlaan** [comment]
I have to concerns:
- How could this be made backwards compatible with existing simple configs?
- How do we prevent identical labels? Note that it is possible to install the same kernel both as a normal kernel image and as an UKI, so just the version is not enough.

**Comment by fabolous005** [comment]
@Biosias yeah templates is probably the better word for what i had in mind.
@AndrewAmmerlaan I'm not sure about backwards compatibilty, but regarding identical labels: they will just be overridden when declaring the label twice and for uki we could do a simple %uki wildcard.

If you had some other solution to this in mind, please share...

**Comment by Biosias** [comment]
Currently the label consit of:

UMC or UMCB flag used to distinguish entries created by the script

Path to the kernel image within its EFI partition

Partition Label or Partition UUID if label is not present, to distinguish entries for the same image residing on multiple partitions at the same time.

The reason label customization wasn't introduced so far is because coming up with naming scheme that would work is hard + user would need to do a lot of testing if their firmware accepts it. What we have now are some sane defaults. And even they are not sufficient as you yourself discovered that 60 character limit.

**Comment by Biosias** [comment]
I'm not opposed to it. Just warning that creating template that works reliably is not trivial

**Comment by fabolous005** [comment]
To allow custom labels i just don't see any other way, for these reasons:
- We should not have exact same lables in efi boot menu
- Therefor each entry should be configurable

The options that are added via the script:
  - UMC/UMCB: %umc
  - Path: %path
  - disk: %disk

Probably %umc should be forced for the user to identify entries that uefi-mkconfig should handle.
```
efi_entries["MyKernel-%kernel on %disk"]="root=/dev/sda1 splash ro whatever"
```

Do see a problem with this?

**Comment by Biosias** [comment]
> Therefor each entry should be configurable

If each entry has to be configurable then why just not use `efibootmgr` directly?

**Comment by Biosias** [comment]
For creating custom label templates I could see it implemented like this:

```
UMC [unique id] [custom label text]
```

in this way, each label will be unique even if the custom label text will be the same on all of them

**Comment by Biosias** [comment]
Regarding multiple cmdline variants. We can have multiple alternative entries that can be generated with different kernel cmdline for each image.

If we configure each entry via `uefi-mkconfig` the kernel installation workflow would look like this:

1. Preconfigure new kernel entry
2. Update kernerl, installkernel will run uefi-mkconfig

Or

1. Update kernel, install kernel will run uefi-mkconfig unconfigured
2. Create configuration for new entry
3. Run uefi-mkconfig again

**Comment by AndrewAmmerlaan** [comment]
> Regarding multiple cmdline variants. We can have multiple alternative entries that can be generated with different kernel cmdline for each image.

Won't the second run of uefi-mkconfig delete the entries created by the first run?

> To allow custom labels i just don't see any other way, for these reasons:
> 
>     * We should not have exact same lables in efi boot menu
> 
>     * Therefor each entry should be configurable

But if each entry has to be configured manually via config file, then what is the point of using `uefi-mkconfig`?

I think it is feasible to *append* some custom text to entries for each cmdline, but I honestly don't see full customization working reliably in practice.

So for example, the config file could look like this:
```
Normal: root=... resume=... quiet splash
Recovery: root= resume= single
```
(though we need something other then `:` because that may be part of the cmdline) 
Which would then create entries:
```
UMC <path to efi file> Normal ...
UMC <path to efi file> Recovery ...
```

The nice thing about using the path is that it is always unique and always contains the `KV+LOCALVERSION`. To make the label shorter the path could be relative to the `\EFI` directory (saves four characters).

**Comment by Biosias** [comment]
> Won't the second run of uefi-mkconfig delete the entries created by the first run?

No.

For example we can have two lines in the config file. On each line there will be a different kernel cmdline configuration.

On each run, `uefi-mkconfig` will for each one kernel image create 2 entries with each having one of the configuration lines from the config file

**Comment by fabolous005** [comment]
Maybe force the use `%kernel` in the custom label...
That way every entry will be unique.

Isn't that the job to automatically create new efi entries when a mew kernel is installed?
By "Configuring each entry" i mean that i want to configure all entries that will be "appended"

**Comment by Biosias** [comment]
> By "Configuring each entry" i mean that i want to configure all entries that will be "appended"

I think we've misunderstood each other with this.

**Comment by Biosias** [comment]
I think this looks reasonable

**Comment by Biosias** [comment]
Hello @fabolous005 ! I'm implementing entry templates in #27 for the next release of uefi-mkconfig. Would you mind taking a look/test it and giving some feedback?

**Comment by fabolous005** [comment]
Just ran the new version with this config:
```bash
declare -Ag kernel_config
kernel_config["Gentoo-%kernel_version booting nvme1n1p3"]="root=PARTUUID=4f68bce3-e8cd-4db1-96e7-fbcaf984b709 rootfstype=btrfs"
kernel_config["LFS-%kernel_version booting nvme0n1p1"]="root=PARTUUID=90c17bbd-e9a2-4a0b-adce-75dbe424fd6f rootfstype=btrfs"
```
did it work for you without `declare`? I _had_ to add `declare -Ag kernel_config`...
however this currently fails, because for some reason it tries to add two entries to the same boot id.
```sh
 * Creating UEFI entry "0200" for "/efi/EFI/Gentoo/vmlinuz-6.10.11-gentoo-dist-hardened-old.efi" found on "nvme1n1p1"
 * No initramfs found for "/efi/EFI/Gentoo/vmlinuz-6.10.11-gentoo-dist-hardened-old.efi".
 * Creating UEFI entry "0200" for "/efi/EFI/Gentoo/vmlinuz-6.10.11-gentoo-dist-hardened-old.efi" found on "nvme1n1p1"
 * No initramfs found for "/efi/EFI/Gentoo/vmlinuz-6.10.11-gentoo-dist-hardened-old.efi".
efibootmgr: Cannot create Boot0200: already exists.
```
Still, thank you for implementing this!!!

**Comment by Biosias** [comment]
Thanks for testing it!

`declare -Ag kernel_config` shouldn't be needed in the config itself because it is declared like this in the script already.

I'll check why it is not working together with the boot id bug. It is still not close to finished so some more development and debugging is needed.

No problem, recommending this feature was a good call thanks! It really does open up a lot more uses cases for uefi-mkconfig.

**Comment by fabolous005** [comment]
Also, as previously mentioned i think sorting sorting will be an issue, as there is no way to determine the order of which the entries are stored in the array.
I see two solutions to this:

1. Create another array that uses numbered keys and the keys of `kernel_config` as values
2. reserve first two digits in `kernel_config` key for numbering the entries

What do you think?

**Comment by Biosias** [comment]
I think ordering it is not an issue. Script just does a for loop over the array so it can be ordered in the config easily just by ordering the `kernel_confg[...]=...` entries in the config in reverse order (I'll be able to fix this).

Is this what you've meant ?

**Comment by fabolous005** [comment]
Yeah, but bash won't keep the order of the config file ([reference](https://stackoverflow.com/questions/29161323/how-to-keep-associative-array-order)).

**Comment by Biosias** [comment]
Well, that is very unfortunate.

In this case, I think it would probably be the best to ditch the associative array and just use variables with plain text.
Something like:

```bash
KERNEL_CMD_CONFIG=""%entry_id %linux_name Linux %kernel_version ; crypt_root=UUID=dcb0ccaf-464c-4e9f-d91c-e59e3655d161 root=/dev/mapper/gentoo-root rootfstype=ext4 resume=/dev/mapper/gentoo-swap dolvm quiet amd_p state=active"
```

then doing something like

```bash
for kernel_config in $(grep "KERNEL_CMD_CONFIG" /etc/default/uefi-mkconfig);do
......
done
```

would keep the order.

**Comment by fabolous005** [comment]
Mmh i don't know about that.
I think sourcing is cleaner. Especially if there may be more config properties in the future.

Of cource having to add two digits to every key in the config makes it a little less user-friendly, but the solution will be straight forward and easily relatively easily implemented.

Something like this for example:
```bash
for key in $(for key in "${!kernel_config[@]}"; do
    echo "$key"
done | sort -n -k1.1,1.2); do
    # Handle sorted iteration
done

```

**Comment by fabolous005** [comment]
What do you think? In the end it's your decision anyways...

**Comment by Biosias** [comment]
I thought about this during the weekend and I will use the grep method for now. If the need arises to use sourcing, changing it will not be time consuming.
