### ISSUE TITLE
microcode handling

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [Biosias/uefi-mkconfig#3]
Dracut by default includes CPU microcode in the initramfs image. However for kernels without an initramfs, or with an initramfs not generated with dracut. We need to update the CPU mircrocode in some other way.

`sys-kernel/linux-firmware[initramfs,-dist-kernel]` and `sys-firmware/intel-microcode[initramfs,-dist-kernel]` currently install `/boot/amd-uc.img` and `/boot/intel-uc.img`. This already works with GRUB, and the next version of installkernel will also be capable of passing this on so it can be used in systemd-boot, UKIs, and efistub.

These images will be `ESP/EFI/Gentoo/amd-uc.img` and  `ESP/EFI/Gentoo/intel-uc.img` (i.e. in the same directory as the kernel image). If these images are present, then we should specify them in the efi entry with additional `initrd=...` arguments. Note that these early microcode images should be specified before any regular initramfs we find.

**Comment by Biosias** [comment]
Hello. thank you for heads up! Will take a look at this.

**Comment by Biosias** [comment]
Pushed https://github.com/Biosias/uefi-mkconfig/commit/53ee0757c233640b6f0ed7dddaea9f2053f61116

**Comment by AndrewAmmerlaan** [comment]
Thanks, one small remark from my side, I think the elif should be an if, because it is not uncommon to have both microcode packages installed (especially on intel systems). If it magically prefers one over the other we might end up accidentally omitting the microcode we actually want.

**Comment by AndrewAmmerlaan** [comment]
Loading both should be fine. AFAIK you can have as many `initrd=` as you want on the cmdline.

**Comment by Biosias** [comment]
In that case, I'll change it.

**Comment by AndrewAmmerlaan** [comment]
Great, Thanks!
